### ISSUE TITLE
Develop an admin tool to determine status of user home value (set/not set)

### ISSUE THREAD

**Issue by michaelpirrello** [dronefly-garden/dronefly#103]
See #102 for prior discussion.

Basically, a way for bot owners/admins to be proactive in determining if there are users who have not used _,user set home <#>_ in order to provide guidance and have that information for dealing with user issues/complaints.

**Comment by synrg** [comment]
This would make a nice extension to `,user list` i think. just another column with y/n indicated for home.

**Comment by synrg** [comment]
You know, for `,user list` to be really useful, though, i think some sort of name search capability needs to be added, so:

`,user list query` -> embed listing all matching users, with the desired column present.

whereas now it just lists `@discorduser is full name (inatlogin) :emoji:` in a rather sloppy list that doesn't line up well.

**Comment by synrg** [comment]
This isn't necessary anymore, since either the global default (North America) or the server default (whatever the server admins have set) will be their default value. This addresses the issue this was trying to help solve which is "why does nothing happen when I press the 🏠 button or use `from home` in a query?"
